# build a workflow that installs and uses pandoc to generate a markdown preview called README.md
# of source.tex

name: Generate Preview

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v2
    
            - name: Install pandoc
             run: |
                sudo apt-get update
                sudo apt-get install pandoc
        
            - name: Generate README.md
              run: pandoc source.tex -o README.md
        

