name: Generate README

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install Pandoc
      run: sudo apt-get install pandoc
    
    - name: Convert LaTeX to Markdown
      run: pandoc source.tex -f latex -t markdown -o README.md

    - name: Commit and push if README.md has changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add README.md
        git commit -m "Auto-update README.md" || exit 0
        git push
